FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY --chown=node:node .next/standalone ./
COPY --chown=node:node .next/static ./.next/static
COPY --chown=node:node public ./public

RUN mkdir -p /app/.next/cache && chown node:node /app/.next/cache

USER node

EXPOSE 3000
CMD ["node", "server.js"]
